# 多模型测试
GET http://127.0.0.1:8080/ai?userInput=你是千问哪个版本

### 返回单个实体
GET http://localhost:8080/ai/returnEntity


### 返回实体列表
GET http://localhost:8080/ai/returnEntityList

### 流式返回 UTF-8
GET http://127.0.0.1:8080/ai/stream?userInput=你是谁
Accept: text/event-stream
Accept-Charset: UTF-8
